### PR TITLE
xbps-uchroot and xbps-uunshare usability improvements

### LINKED ISSUE #203: xbps-uchroot: tries to interpret options in cmdargs as its own
``` sh
$ xbps-query -p pkgver xbps
xbps-0.51_10
```

According to:

```
Usage: xbps-uchroot [-b src:dest] [-O -t -o <opts>] <dir> <cmd> [<cmdargs>]
```

I should be able to pass arguments to a command without quoting, etc.
However, it appears that `xbps-uchroot` interprets (and rejects) at least some flags meant for a command as being meant for `xbps-uchroot` itself.

Steps to reproduce:

With a prepared chroot environment in `mnt`, say Void Linux itself, run:

``` sh
$ sudo xbps-uchroot mnt /usr/bin/xbps-install -y extlinux
xbps-uchroot: invalid option -- 'y'
```

### PR DESCRIPTION
**Pull request by Duncaen**
This fixes #203 and #204 for `xbps-uchroot` and `xbps-uunshare`.
Not sure if it should support `.` to use the current directory as chrootdir and if there should be more error checks to make sure the chrootdir exists.

### CODE REVIEW

File: bin/xbps-uunshare/main.c [hunk 1]
```diff
@@ -157,14 +157,22 @@ main(int argc, char **argv)
...
+	chrootdir = argv[-1];
 	cmd = argv[1];
 	cmdargs = argv + 1;
 
 	/* Never allow chrootdir == / */
 	if (strcmp(chrootdir, "/") == 0)
 		die("/ is not allowed to be used as chrootdir");
 
+	/* Make chrootdir absolute */
+	if (chrootdir[0] != '/') {
```
Comment (ebfe) [inline bin/xbps-uunshare/main.c]: use realpath(3)?

File: bin/xbps-uunshare/main.c [hunk 2]
```diff
@@ -157,14 +157,22 @@ main(int argc, char **argv)
 	if (argc < 2)
 		usage(argv0);
 
-	chrootdir = argv[0];
+	chrootdir = argv[-1];
```
Comment (ebfe) [inline bin/xbps-uunshare/main.c]: huh?

Comment (Duncaen) [inline bin/xbps-uunshare/main.c]: huh, no idea how this happened.
