### PR TITLE
xbps-remove: fix --dry-run for --clean-cache

### LINKED ISSUE #165: xbps-remove : no dry run on obsolete packages removal
hello,
option `-n` does not work, at least with `-O` : obsolete packages are removed.
```
$ sudo xbps-remove --version
XBPS: 0.51 API: 20151030 GIT: UNSET
```
```
$ sudo xbps-remove -n -O
Removed python-setuptools-20.6.7_1.noarch.xbps from cachedir (obsolete)
Removed python-urllib3-1.15_1.noarch.xbps from cachedir (obsolete)
[...]
```
on 2nd invocation, nothing found, so removal has really been done:
```
$ sudo xbps-remove -n -O
(nothing)
```

### PR DESCRIPTION
**Pull request by jantatje**
`xbps-remove --clean-cache --dry-run` did not consider the
--dry-run flag, this has been fixed.

Fixes #165.

### CODE REVIEW

**Comment by Duncaen** [comment]
Why pass a char[]?

**Comment by jantatje** [comment]
I can change it to pass whatever you want, somehow just read the variable name "arg" and thought of a string. (Even though it's void*!) Should I rather pass a bool* or an int* and use the first bit as flag? I can change it to whatever you think it's best.

**Comment by jantatje** [comment]
I changed it to pass a bool pointer.

File: bin/xbps-remove/clean-cache.c [hunk 1]
```diff
@@ -38,12 +38,19 @@
...
 static int
 cleaner_cb(struct xbps_handle *xhp, xbps_object_t obj,
-		const char *key _unused, void *arg _unused,
+		const char *key _unused, void *arg,
 		bool *done _unused)
 {
 	xbps_dictionary_t repo_pkgd;
 	const char *binpkg, *rsha256;
 	char *binpkgsig, *pkgver, *arch;
+	bool drun;
```
Comment (xtraeme) [inline bin/xbps-remove/clean-cache.c]: `bool drun = false;`

File: bin/xbps-remove/clean-cache.c [hunk 2]
```diff
@@ -38,12 +38,19 @@
...
+
+	/* Extract drun (dry-run) flag from arg*/
+	if (arg != NULL)
+		drun = *(bool*)arg;
+	else
```
Comment (xtraeme) [inline bin/xbps-remove/clean-cache.c]: WIth the var initialized previously you can skip the `else` conditional.

**Comment by jantatje** [comment]
Done. Please re-review.

**Comment by Gottox** [comment]
:+1:

**Comment by avoidr** [comment]
Hello. I just came across this bug myself.
When is the next release/revision of xbps going to be?
